-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 14:25:34 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema base_teste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base_teste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base_teste` DEFAULT CHARACTER SET utf8mb4 ;
USE `base_teste` ;

-- -----------------------------------------------------
-- Table `base_teste`.`pdc_teste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_teste`.`pdc_teste` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` INT(11) NOT NULL,
  `report` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '',
  `nivel1` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '',
  `nivel2` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `nivel3` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `nivel4` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `nivel4` (`nivel4` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `base_teste`.`ledger_teste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_teste`.`ledger_teste` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref` INT(11) NULL DEFAULT NULL,
  `data` DATE NOT NULL,
  `credito` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '',
  `debito` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '',
  `valor` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ref` (`ref` ASC),
  CONSTRAINT `Contas`
    FOREIGN KEY (`credito`)
    REFERENCES `base_teste`.`pdc_teste` (`nivel4`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Contas2`
    FOREIGN KEY (`debito`)
    REFERENCES `base_teste`.`pdc_teste` (`nivel4`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `base_teste`.`cap_teste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_teste`.`cap_teste` (
  `AP` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Credor` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  INDEX `AP` (`AP` ASC),
  CONSTRAINT `ref`
    FOREIGN KEY ()
    REFERENCES `base_teste`.`ledger_teste` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `base_teste`.`car_teste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_teste`.`car_teste` (
  `AR` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Devedor` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `Valor` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`AR`),
  CONSTRAINT `ref`
    FOREIGN KEY ()
    REFERENCES `base_teste`.`ledger_teste` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `base_teste`.`extrato_teste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_teste`.`extrato_teste` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `extrato` VARCHAR(11) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `conta` VARCHAR(11) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `Id_Transacoes`
    FOREIGN KEY (`id`)
    REFERENCES `base_teste`.`ledger_teste` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `base_teste`.`descricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_teste`.`descricao` (
  `iddsc` INT NOT NULL,
  `descricao` LONGTEXT NULL,
  PRIMARY KEY (`iddsc`),
  CONSTRAINT `id`
    FOREIGN KEY ()
    REFERENCES `base_teste`.`ledger_teste` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
